panda_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.05 # this timeout parameter is actually ignored by servo
  # kinematics_solver_attempts: 1.0
  # mode: gd_c # see bio_ik for other modes, but gd_c (gradient descent) has the best performance

# $(arg arm_id)_manipulator: *arm_config
