$(arg arm_id)_arm: &arm_config
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005

$(arg arm_id)_manipulator: *arm_config
